name: brayheta
favicon: null
layout_spectrum: 0.89320497517474
typography_spectrum: 0.5933701435569674
title: jewellery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060405'
    - '#ffffff'
    - '#c5ba9c'
    - '#9d8e61'
    - '#5c4d29'
  brandStrength: 0.6803391997236758
  lightness: 0.4837402405682951
  saturation: 0.9135437852237374
  rhythmicContrast: 0.3260172540321946
purpose: []
