name: brayheta
favicon: null
layout_spectrum: 0.66708
typography_spectrum: 0.5933701435569674
title: Jewellery by Anthony Bray-Heta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060405'
    - '#ffffff'
    - '#c5ba9c'
    - '#9d8e61'
    - '#5c4d29'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
